apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: "{{ .Values.movieService.image }}:{{ .Values.movieService.tag }}"
        ports:
        - containerPort: {{ .Values.movieService.port }}
        env:
        - name: DATABASE_URI
          value: "postgresql://{{ .Values.movieDb.user }}:{{ .Values.movieDb.password }}@movie-db/{{ .Values.movieDb.dbName }}"
        - name: CAST_SERVICE_HOST_URL
          value: "http://cast-service:{{ .Values.castService.port }}/api/v1/casts/"
